//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RECEBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_RECEBER()
        {
            this.RECEBIDO = new HashSet<RECEBIDO>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PARCELA_ID { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public decimal VALOR_PAGO { get; set; }
        public decimal VALOR_RESTANTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEBIDO> RECEBIDO { get; set; }
    }
}
