//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAIXA_OPEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAIXA_OPEN()
        {
            this.CAIXA = new HashSet<CAIXA>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATA_ABERTURA { get; set; }
        public System.TimeSpan HORA { get; set; }
        public decimal VALOR { get; set; }
        public string RESPONSAVEL_ABERTURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAIXA> CAIXA { get; set; }
    }
}
