//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAIXA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAIXA()
        {
            this.ENTRADA_CAIXA = new HashSet<ENTRADA_CAIXA>();
            this.SAIDA_CAIXA = new HashSet<SAIDA_CAIXA>();
            this.SANGRIA = new HashSet<SANGRIA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID { get; set; }
        public int CAIXA_CLOSE_ID { get; set; }
        public int CAIXA_OPEN_ID { get; set; }
        public string NOME { get; set; }
        public int SALDO { get; set; }
    
        public virtual CAIXA_CLOSE CAIXA_CLOSE { get; set; }
        public virtual CAIXA_OPEN CAIXA_OPEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADA_CAIXA> ENTRADA_CAIXA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAIDA_CAIXA> SAIDA_CAIXA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANGRIA> SANGRIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
