//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.ORCAMENTO_VENDA = new HashSet<ORCAMENTO_VENDA>();
            this.ORCAMENTO_SERVICO = new HashSet<ORCAMENTO_SERVICO>();
        }
    
        public long ID { get; set; }
        public int CIDADE_ID { get; set; }
        public int SUBGRUPO_CLIENTE_ID { get; set; }
        public string TIPO { get; set; }
        public string NOME { get; set; }
        public string SEXO { get; set; }
        public string FOTO { get; set; }
        public System.DateTime DATA_CADASTRO { get; set; }
        public string EMAIL { get; set; }
        public string CONTATO { get; set; }
        public string CEP { get; set; }
        public string NUMERO { get; set; }
        public string RUA { get; set; }
        public string BAIRRO { get; set; }
        public string CPF_CNPJ { get; set; }
        public string RG_IE { get; set; }
    
        public virtual CIDADE CIDADE { get; set; }
        public virtual SUBGRUPO_CLIENTE SUBGRUPO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_VENDA> ORCAMENTO_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_SERVICO> ORCAMENTO_SERVICO { get; set; }
    }
}
