//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.FATURAMENTO_COMPRA = new HashSet<FATURAMENTO_COMPRA>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ORCAMENTO_SERVICO_ID { get; set; }
        public Nullable<int> ORCAMENTO_COMPRA_ID { get; set; }
        public System.DateTime DATA_COMPRA { get; set; }
        public System.TimeSpan HORA_COMPRA { get; set; }
        public decimal QUANTIDADE_TOTAL { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public decimal DESCONTO_REAIS { get; set; }
        public decimal DESCONTO_PORCENTO { get; set; }
        public decimal ACRESCIMO_REAIS { get; set; }
        public decimal ACRESCIMO_PORCENTAGEM { get; set; }
        public decimal TOTAL { get; set; }
    
        public virtual ORCAMENTO_COMPRA ORCAMENTO_COMPRA { get; set; }
        public virtual ORCAMENTO_SERVICO ORCAMENTO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURAMENTO_COMPRA> FATURAMENTO_COMPRA { get; set; }
    }
}
