//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIE_PAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIE_PAGAMENTO()
        {
            this.ESPECIEPAGAMENTO_FATURAMENTOVENDA = new HashSet<ESPECIEPAGAMENTO_FATURAMENTOVENDA>();
            this.FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO = new HashSet<FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESPECIEPAGAMENTO_FATURAMENTOVENDA> ESPECIEPAGAMENTO_FATURAMENTOVENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO> FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO { get; set; }
    }
}
