//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURAMENTO_VENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATURAMENTO_VENDA()
        {
            this.ESPECIEPAGAMENTO_FATURAMENTOVENDA = new HashSet<ESPECIEPAGAMENTO_FATURAMENTOVENDA>();
            this.PARCELAS_VENDAS = new HashSet<PARCELAS_VENDAS>();
            this.FORMA_RECEBIMENTO_PAGAMENTO = new HashSet<FORMA_RECEBIMENTO_PAGAMENTO>();
        }
    
        public int ID { get; set; }
        public int VENDA_ID { get; set; }
        public int CONDICAO_PAGAMENTO_ID { get; set; }
        public decimal ACRESCIMO { get; set; }
        public decimal DESCONTO { get; set; }
        public decimal SEGURO { get; set; }
        public decimal FRETE { get; set; }
        public decimal OUTROS { get; set; }
    
        public virtual CONDICAO_PAGAMENTO CONDICAO_PAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESPECIEPAGAMENTO_FATURAMENTOVENDA> ESPECIEPAGAMENTO_FATURAMENTOVENDA { get; set; }
        public virtual VENDA VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCELAS_VENDAS> PARCELAS_VENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMA_RECEBIMENTO_PAGAMENTO> FORMA_RECEBIMENTO_PAGAMENTO { get; set; }
    }
}
