//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURAMENTO_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATURAMENTO_COMPRA()
        {
            this.FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO = new HashSet<FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO>();
            this.PARCELAR_COMPRA = new HashSet<PARCELAR_COMPRA>();
        }
    
        public long ID { get; set; }
        public long COMPRA_ID { get; set; }
        public int CONDICAO_PAGAMENTO_ID { get; set; }
        public decimal ACRESCIMO { get; set; }
        public decimal DESCONTO { get; set; }
        public decimal SEGURO { get; set; }
        public decimal FRETE { get; set; }
        public decimal OUTROS { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual CONDICAO_PAGAMENTO CONDICAO_PAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO> FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCELAR_COMPRA> PARCELAR_COMPRA { get; set; }
    }
}
