//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR_PRODUTOS
    {
        public int FORNECEDOR_ID { get; set; }
        public int PRODUTOS_ID { get; set; }
        public System.DateTime DATA_CONTRATO { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual PRODUTOS PRODUTOS { get; set; }
    }
}
