//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORNECEDOR()
        {
            this.FORNECEDOR_PRODUTOS = new HashSet<FORNECEDOR_PRODUTOS>();
            this.ORCAMENTO_COMPRA = new HashSet<ORCAMENTO_COMPRA>();
        }
    
        public int ID { get; set; }
        public int CIDADE_ID { get; set; }
        public string FANTASIA { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public string RESPONSAVEL { get; set; }
        public string EMAIL { get; set; }
        public string CONTATO { get; set; }
        public string CEP { get; set; }
        public string NUMERO { get; set; }
        public string RUA { get; set; }
        public string BAIRRO { get; set; }
    
        public virtual CIDADE CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECEDOR_PRODUTOS> FORNECEDOR_PRODUTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_COMPRA> ORCAMENTO_COMPRA { get; set; }
    }
}
