//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARCA_ORCAMENTOSERVICO
    {
        public int MARCA_ID { get; set; }
        public long ORCAMENTO_SERVICO_ID { get; set; }
        public long SERVICOS_ID { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual ORCAMENTO_SERVICO ORCAMENTO_SERVICO { get; set; }
        public virtual SERVICOS SERVICOS { get; set; }
    }
}
