//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cs_erpEntities : DbContext
    {
        public cs_erpEntities()
            : base("name=cs_erpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_PAGAR> A_PAGAR { get; set; }
        public virtual DbSet<A_RECEBER> A_RECEBER { get; set; }
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<CAIXA> CAIXA { get; set; }
        public virtual DbSet<CAIXA_CLOSE> CAIXA_CLOSE { get; set; }
        public virtual DbSet<CAIXA_OPEN> CAIXA_OPEN { get; set; }
        public virtual DbSet<CFOP> CFOP { get; set; }
        public virtual DbSet<CIDADE> CIDADE { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<CONDICAO_PAGAMENTO> CONDICAO_PAGAMENTO { get; set; }
        public virtual DbSet<ENTRADA_CAIXA> ENTRADA_CAIXA { get; set; }
        public virtual DbSet<ESPECIE_PAGAMENTO> ESPECIE_PAGAMENTO { get; set; }
        public virtual DbSet<ESPECIEPAGAMENTO_FATURAMENTOVENDA> ESPECIEPAGAMENTO_FATURAMENTOVENDA { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<FATURAMENTO_COMPRA> FATURAMENTO_COMPRA { get; set; }
        public virtual DbSet<FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO> FATURAMENTO_COMPRA_has_ESPECIE_PAGAMENTO { get; set; }
        public virtual DbSet<FATURAMENTO_VENDA> FATURAMENTO_VENDA { get; set; }
        public virtual DbSet<FORMA_RECEBIMENTO_PAGAMENTO> FORMA_RECEBIMENTO_PAGAMENTO { get; set; }
        public virtual DbSet<FORNECEDOR> FORNECEDOR { get; set; }
        public virtual DbSet<FORNECEDOR_PRODUTOS> FORNECEDOR_PRODUTOS { get; set; }
        public virtual DbSet<FUNCAO> FUNCAO { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<GRUPO_PRODUTO> GRUPO_PRODUTO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MARCA_ORCAMENTOSERVICO> MARCA_ORCAMENTOSERVICO { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<ORCAMENTO_COMPRA> ORCAMENTO_COMPRA { get; set; }
        public virtual DbSet<ORCAMENTO_SERVICO> ORCAMENTO_SERVICO { get; set; }
        public virtual DbSet<ORCAMENTO_VENDA> ORCAMENTO_VENDA { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PARCELAR_COMPRA> PARCELAR_COMPRA { get; set; }
        public virtual DbSet<PARCELAS_VENDAS> PARCELAS_VENDAS { get; set; }
        public virtual DbSet<PONTO> PONTO { get; set; }
        public virtual DbSet<PRODUTO_ORCAMENTOVENDA> PRODUTO_ORCAMENTOVENDA { get; set; }
        public virtual DbSet<PRODUTO_ORCCAMENTOCOMPRA> PRODUTO_ORCCAMENTOCOMPRA { get; set; }
        public virtual DbSet<PRODUTOS> PRODUTOS { get; set; }
        public virtual DbSet<RECEBIDO> RECEBIDO { get; set; }
        public virtual DbSet<REGISTRO> REGISTRO { get; set; }
        public virtual DbSet<REGISTRO_EMPRESA> REGISTRO_EMPRESA { get; set; }
        public virtual DbSet<SAIDA_CAIXA> SAIDA_CAIXA { get; set; }
        public virtual DbSet<SANGRIA> SANGRIA { get; set; }
        public virtual DbSet<SERVICOS> SERVICOS { get; set; }
        public virtual DbSet<SUBGRUPO_CLIENTE> SUBGRUPO_CLIENTE { get; set; }
        public virtual DbSet<SUBGRUPO_PRODUTO> SUBGRUPO_PRODUTO { get; set; }
        public virtual DbSet<TIPO_UNIDADE_PRODUTO> TIPO_UNIDADE_PRODUTO { get; set; }
        public virtual DbSet<TRIBUTACAO_PRODUTO> TRIBUTACAO_PRODUTO { get; set; }
        public virtual DbSet<TRIBUTOS_PRODUTO> TRIBUTOS_PRODUTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VENDA> VENDA { get; set; }
    }
}
