//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELAS_VENDAS
    {
        public int ID { get; set; }
        public int FATURAMENTO_VENDA_ID { get; set; }
        public int NUMERO { get; set; }
        public System.DateTime DATA_CRIACAO { get; set; }
        public System.DateTime DATA_VENCIMENTO { get; set; }
        public decimal VALOR_PARCELA { get; set; }
        public decimal JUROS_VENCIMENTO { get; set; }
        public decimal DESCONTO { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public int VENCIDA { get; set; }
        public int PAGA { get; set; }
    
        public virtual FATURAMENTO_VENDA FATURAMENTO_VENDA { get; set; }
    }
}
