//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PONTO
    {
        public int ID { get; set; }
        public int REGISTRO_ID { get; set; }
        public int USUARIO_ID { get; set; }
        public string DESCRICAO { get; set; }
        public System.TimeSpan HORA_EXTRA { get; set; }
        public System.TimeSpan HORA_DEFICIT { get; set; }
    
        public virtual REGISTRO REGISTRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
