//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTOS()
        {
            this.FORNECEDOR_PRODUTOS = new HashSet<FORNECEDOR_PRODUTOS>();
            this.PRODUTO_ORCAMENTOVENDA = new HashSet<PRODUTO_ORCAMENTOVENDA>();
            this.PRODUTO_ORCCAMENTOCOMPRA = new HashSet<PRODUTO_ORCCAMENTOCOMPRA>();
        }
    
        public int ID { get; set; }
        public int CFOP_ID { get; set; }
        public string TRIBUTACAO_PRODUTO_NCM { get; set; }
        public int SUBGRUPO_PRODUTO_ID { get; set; }
        public int TIPO_UNIDADE_PRODUTO_ID { get; set; }
        public string IMAGEM { get; set; }
        public string GTIN { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public int QUANTIDADE_ESTOQUE { get; set; }
        public int ESTOQUE_MINIMO { get; set; }
        public int ESTOQUE_MAXIMO { get; set; }
        public decimal VALOR_VENDA { get; set; }
        public decimal VALOR_VENDA_MAX { get; set; }
        public decimal VALOR_VENDA_MIN { get; set; }
        public decimal VALOR_COMPRA { get; set; }
        public decimal VALOR_MEDIO_LUCRO { get; set; }
        public decimal PESO_BRUTO { get; set; }
        public decimal PESO_LIQUIDO { get; set; }
    
        public virtual CFOP CFOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECEDOR_PRODUTOS> FORNECEDOR_PRODUTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ORCAMENTOVENDA> PRODUTO_ORCAMENTOVENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ORCCAMENTOCOMPRA> PRODUTO_ORCCAMENTOCOMPRA { get; set; }
        public virtual SUBGRUPO_PRODUTO SUBGRUPO_PRODUTO { get; set; }
        public virtual TIPO_UNIDADE_PRODUTO TIPO_UNIDADE_PRODUTO { get; set; }
        public virtual TRIBUTACAO_PRODUTO TRIBUTACAO_PRODUTO { get; set; }
    }
}
