//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_ORCAMENTOVENDA
    {
        public long ORCAMENTO_VENDA_ID { get; set; }
        public int PRODUTOS_ID { get; set; }
        public decimal QUANTIDADE { get; set; }
        public decimal VALOR_UNIDADE { get; set; }
        public decimal VALOR_TOTAL { get; set; }
    
        public virtual ORCAMENTO_VENDA ORCAMENTO_VENDA { get; set; }
        public virtual PRODUTOS PRODUTOS { get; set; }
    }
}
