//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEBIDO
    {
        public long ID { get; set; }
        public long A_RECEBER_ID { get; set; }
        public System.DateTime DATA_RECEBIMENTO { get; set; }
        public System.TimeSpan HORA { get; set; }
        public string NOTA { get; set; }
    
        public virtual A_RECEBER A_RECEBER { get; set; }
    }
}
