//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRO()
        {
            this.PONTO = new HashSet<PONTO>();
        }
    
        public int ID { get; set; }
        public string USUARIO_NOME { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan HORA_ENTRADA { get; set; }
        public Nullable<System.TimeSpan> HORA_SAIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PONTO> PONTO { get; set; }
    }
}
