//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_EMPRESA
    {
        public int ID { get; set; }
        public int CIDADE_ID { get; set; }
        public string FANTASIA { get; set; }
        public string RAZAO { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string BAIRRO { get; set; }
        public string RUA { get; set; }
        public string NUMERO { get; set; }
        public string CONTATO { get; set; }
        public string EMAIL { get; set; }
        public string MAC { get; set; }
        public string COD_HD { get; set; }
        public string SERIAL { get; set; }
    
        public virtual CIDADE CIDADE { get; set; }
    }
}
