//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANGRIA
    {
        public int ID { get; set; }
        public int CAIXA_ID { get; set; }
        public System.DateTime DATA_SANGRIA { get; set; }
        public System.TimeSpan HORA { get; set; }
        public string RESPONSAVEL_SANGRIA { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual CAIXA CAIXA { get; set; }
    }
}
