//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICOS()
        {
            this.MARCA_ORCAMENTOSERVICO = new HashSet<MARCA_ORCAMENTOSERVICO>();
        }
    
        public long ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public decimal VALOR { get; set; }
        public decimal ALIQUOTA_ISS { get; set; }
        public decimal PRECO_SUGERIDO { get; set; }
        public decimal PRECO_MINIMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARCA_ORCAMENTOSERVICO> MARCA_ORCAMENTOSERVICO { get; set; }
    }
}
