//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIBUTOS_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIBUTOS_PRODUTO()
        {
            this.TRIBUTACAO_PRODUTO = new HashSet<TRIBUTACAO_PRODUTO>();
        }
    
        public int ID { get; set; }
        public int ICMS_VENDA { get; set; }
        public int CFOP_ENTRADA { get; set; }
        public int CFOP_SAIDA { get; set; }
        public int CST_IPI_ENTRADA { get; set; }
        public int CST_IPI_SAIDA { get; set; }
        public int CST_PIS_ENTRADA { get; set; }
        public int CST_PIS_SAIDA { get; set; }
        public int CST_COFINS_ENTRADA { get; set; }
        public int CST_COFINS_SAIDA { get; set; }
        public decimal IPI_ENTRADA_PORCENTO { get; set; }
        public decimal IPI_SAIDA_PORCENTO { get; set; }
        public decimal PIS_ENTRADA_PORCENTO { get; set; }
        public decimal PIS_SAIDA_PORCENTO { get; set; }
        public decimal COFINS_ENTRADA_PORCENTO { get; set; }
        public decimal COFINS_SAIDA_PORCENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIBUTACAO_PRODUTO> TRIBUTACAO_PRODUTO { get; set; }
    }
}
