//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ORCAMENTO_COMPRA = new HashSet<ORCAMENTO_COMPRA>();
            this.ORCAMENTO_SERVICO = new HashSet<ORCAMENTO_SERVICO>();
            this.ORCAMENTO_VENDA = new HashSet<ORCAMENTO_VENDA>();
            this.PONTO = new HashSet<PONTO>();
        }
    
        public int ID { get; set; }
        public int CIDADE_ID { get; set; }
        public int CAIXA_ID { get; set; }
        public int FUNCAO_ID { get; set; }
        public int BANCO_ID { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public System.DateTime DATA_CADASTRO { get; set; }
        public string ADMINISTRADOR { get; set; }
        public string FOTO { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string CONTATO { get; set; }
        public string CEP { get; set; }
        public string NUMERO { get; set; }
        public string RUA { get; set; }
        public string BAIRRO { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string CARTEIRA_TRABALHO { get; set; }
        public string PIS { get; set; }
        public string EXAME_ADMISSAO { get; set; }
        public string EXAME_DEMISSAO { get; set; }
    
        public virtual BANCO BANCO { get; set; }
        public virtual CAIXA CAIXA { get; set; }
        public virtual CIDADE CIDADE { get; set; }
        public virtual FUNCAO FUNCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_COMPRA> ORCAMENTO_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_SERVICO> ORCAMENTO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_VENDA> ORCAMENTO_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PONTO> PONTO { get; set; }
    }
}
