//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDA()
        {
            this.FATURAMENTO_VENDA = new HashSet<FATURAMENTO_VENDA>();
        }
    
        public int ID { get; set; }
        public Nullable<long> ORCAMENTO_SERVICO_ID { get; set; }
        public Nullable<long> ORCAMENTO_VENDA_ID { get; set; }
        public System.DateTime DATA_VENDA { get; set; }
        public System.TimeSpan HORA { get; set; }
        public int QUATIDADE_TOTAL { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public decimal DESCONTO_REAIS { get; set; }
        public decimal ACRESCIMO_REAIS { get; set; }
        public decimal DESCONTO_PORCENTO { get; set; }
        public decimal ACRESCIMO_PORCENTO { get; set; }
        public decimal TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURAMENTO_VENDA> FATURAMENTO_VENDA { get; set; }
        public virtual ORCAMENTO_SERVICO ORCAMENTO_SERVICO { get; set; }
        public virtual ORCAMENTO_VENDA ORCAMENTO_VENDA { get; set; }
    }
}
